name: CI Checks
run-name: This will use Rubocop to check for any offenses
on: 
  push:
    branches:
      - 'pipeline'
jobs:
  run-linter:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v1
      - name: RuboCop Linter
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby and Install Dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rspec